import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Star } from "@/components/ui/star"
import { Random } from "@/common/random"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const random = new Random(0);

const backgroundItems = Array.from({ length: 30 }, (_, i) => {
  const size = random.nextInt(1,4)
  return {
    id: i,
    x: random.nextInt(0, 100),
    y: random.nextInt(0, 100),
    w: size,
    h: size
  }
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative w-full h-screen bg-gray-900 overflow-hidden">
          {backgroundItems.map((item) => (
            <Star
              key={item.id}
              className={`absolute text-red-500`}
              style={{ left: `${item.x}%`, top: `${item.y}%`, width: `${item.w}px`, height: `${item.h}px` }}
            />
          ))}
          {children}
        </div>
      </body>
    </html>
  );
}
